// Command genapi regenerates the root compatibility facade from the exported
// declarations in internal/engine. The domain packages remain the preferred
// organization for large applications; the root facade is intentionally flat.
package main

import (
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type exports struct {
	types  []string
	consts []string
	vars   []string
	funcs  []string
}

func main() {
	root, err := findModuleRoot()
	must(err)
	e, err := scan(filepath.Join(root, "internal", "engine"))
	must(err)

	var b strings.Builder
	b.WriteString("// Code generated by go generate; DO NOT EDIT.\n")
	b.WriteString("package ink\n\n")
	b.WriteString("import engine \"github.com/frudas24/inkgo/internal/engine\"\n\n")

	if len(e.types) > 0 {
		b.WriteString("type (\n")
		for _, name := range e.types {
			fmt.Fprintf(&b, "\t%s = engine.%s\n", name, name)
		}
		b.WriteString(")\n\n")
	}
	if len(e.consts) > 0 {
		b.WriteString("const (\n")
		for _, name := range e.consts {
			fmt.Fprintf(&b, "\t%s = engine.%s\n", name, name)
		}
		b.WriteString(")\n\n")
	}
	if len(e.vars)+len(e.funcs) > 0 {
		b.WriteString("var (\n")
		for _, name := range e.vars {
			fmt.Fprintf(&b, "\t%s = engine.%s\n", name, name)
		}
		for _, name := range e.funcs {
			fmt.Fprintf(&b, "\t%s = engine.%s\n", name, name)
		}
		b.WriteString(")\n")
	}

	formatted, err := format.Source([]byte(b.String()))
	must(err)
	must(os.WriteFile(filepath.Join(root, "api.go"), formatted, 0o644))
}

func findModuleRoot() (string, error) {
	dir, err := os.Getwd()
	if err != nil {
		return "", err
	}
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("go.mod not found")
		}
		dir = parent
	}
}

func scan(dir string) (exports, error) {
	fset := token.NewFileSet()
	pkgs, err := parser.ParseDir(fset, dir, func(info os.FileInfo) bool {
		return !strings.HasSuffix(info.Name(), "_test.go")
	}, 0)
	if err != nil {
		return exports{}, err
	}
	pkg := pkgs["engine"]
	if pkg == nil {
		return exports{}, fmt.Errorf("engine package not found in %s", dir)
	}

	var out exports
	seen := map[string]bool{}
	add := func(dst *[]string, name string) {
		if !ast.IsExported(name) || seen[name] {
			return
		}
		seen[name] = true
		*dst = append(*dst, name)
	}
	for _, file := range pkg.Files {
		for _, decl := range file.Decls {
			switch d := decl.(type) {
			case *ast.FuncDecl:
				if d.Recv == nil {
					add(&out.funcs, d.Name.Name)
				}
			case *ast.GenDecl:
				for _, spec := range d.Specs {
					switch s := spec.(type) {
					case *ast.TypeSpec:
						add(&out.types, s.Name.Name)
					case *ast.ValueSpec:
						for _, n := range s.Names {
							switch d.Tok {
							case token.CONST:
								add(&out.consts, n.Name)
							case token.VAR:
								add(&out.vars, n.Name)
							}
						}
					}
				}
			}
		}
	}
	sort.Strings(out.types)
	sort.Strings(out.consts)
	sort.Strings(out.vars)
	sort.Strings(out.funcs)
	return out, nil
}

func must(err error) {
	if err != nil {
		fmt.Fprintln(os.Stderr, "genapi:", err)
		os.Exit(1)
	}
}
